# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

name: Build

on:
  push:
    branches-ignore:
      - dev
      - unstable
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Docker
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build
